### ISSUE TITLE
License

### ISSUE THREAD

**Issue by muhamm-ad** [alaurent34/mtl_street_sign_to_curblr#1]
Hi,

Could you please specify which license applies to this project? If possible, could you add it to the repository?

Common licenses to consider:
- [MIT License](https://opensource.org/licenses/MIT)
- [Apache 2.0 License](https://opensource.org/licenses/Apache-2.0)
- [GPLv3 License](https://www.gnu.org/licenses/gpl-3.0.html)

Thank you!

**Comment by alaurent34** [comment]
Hi, 

Thanks for your interest on this project. I will update the licence and document a bit more the project in the following days.

**Comment by muhamm-ad** [comment]
Thanks, I appreciate the effort.

**Comment by alaurent34** [comment]
I have added the License to the project. Please note that I also switch the default branch from Master to main. 

#1b88332
